function p = dfd_dq_cartpole(x_d,th_d,dx_d,dth_d,u_th_d,m_cart,m_mass,l,g)
%DFD_DQ_CARTPOLE
%    P = DFD_DQ_CARTPOLE(X_D,TH_D,DX_D,DTH_D,U_TH_D,M_CART,M_MASS,L,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    06-Nov-2016 13:37:25

p = reshape([0.0,0.0,dth_d.*l.*m_mass.*sin(th_d).*-2.0,0.0],[2,2]);
