function p = dfdq_cartpole(x_d,th_d,dx_d,dth_d,u_th_d,m_cart,m_mass,l,g)
%DFDQ_CARTPOLE
%    P = DFDQ_CARTPOLE(X_D,TH_D,DX_D,DTH_D,U_TH_D,M_CART,M_MASS,L,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    31-Oct-2016 00:31:29

p = reshape([0.0,0.0,dth_d.^2.*l.*m_mass.*sin(th_d),0.0],[2,2]);
