function p = M_cartpole(x,th,dx,dth,m_cart,m_mass,l,u_th,g)
%M_CARTPOLE
%    P = M_CARTPOLE(X,TH,DX,DTH,M_CART,M_MASS,L,U_TH,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    31-Oct-2016 00:31:28

t2 = sin(th);
t3 = l.*m_mass.*t2;
t4 = cos(th);
t5 = l.^2;
p = reshape([m_cart+m_mass,t3,t3,m_mass.*t2.^2.*t5+m_mass.*t4.^2.*t5],[2,2]);
