function p = dfdu_cartpole(x_d,th_d,dx_d,dth_d,u_th_d,m_cart,m_mass,l,g)
%DFDU_CARTPOLE
%    P = DFDU_CARTPOLE(X_D,TH_D,DX_D,DTH_D,U_TH_D,M_CART,M_MASS,L,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    06-Nov-2016 13:07:44

p = [0.0;1.0];
