function p = dMdq_cartpole(x_d,th_d,dx_d,dth_d,u_f_d,m_cart,m_mass,l,g)
%DMDQ_CARTPOLE
%    P = DMDQ_CARTPOLE(X_D,TH_D,DX_D,DTH_D,U_F_D,M_CART,M_MASS,L,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Nov-2016 10:38:27

t2 = sin(th_d);
t3 = l.*m_mass.*t2;
p = reshape([0.0,0.0,0.0,0.0,0.0,t3,t3,0.0],[2,2,2]);
