function p = ff_cartpole(x,th,dx,dth,m_cart,m_mass,l,u_f,g)
%FF_CARTPOLE
%    P = FF_CARTPOLE(X,TH,DX,DTH,M_CART,M_MASS,L,U_F,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Nov-2016 10:38:25

t2 = sin(th);
p = [u_f-dth.^2.*l.*m_mass.*t2;g.*l.*m_mass.*t2];
