function p = KE_cartpolel(x,th,dx,dth,m_cart,m_mass,l,u_f,g)
%KE_CARTPOLEL
%    P = KE_CARTPOLEL(X,TH,DX,DTH,M_CART,M_MASS,L,U_F,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Nov-2016 10:38:25

t2 = dx-dth.*l.*cos(th);
t3 = sin(th);
p = dx.^2.*m_cart.*(1.0./2.0)+m_mass.*t2.^2.*(1.0./2.0)+dth.^2.*l.^2.*m_mass.*t3.^2.*(1.0./2.0);
