function p = P_mass(x,th,dx,dth,m_cart,m_mass,l,u_f,g)
%P_MASS
%    P = P_MASS(X,TH,DX,DTH,M_CART,M_MASS,L,U_F,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Nov-2016 10:38:24

p = [x-l.*sin(th);l.*cos(th)];
