function p = PE_cartpole(x,th,dx,dth,m_cart,m_mass,l,u_f,g)
%PE_CARTPOLE
%    P = PE_CARTPOLE(X,TH,DX,DTH,M_CART,M_MASS,L,U_F,G)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Nov-2016 10:38:26

p = g.*l.*m_mass.*cos(th);
