function R = Raxisangle(k,theta)
%Raxisangle : rotation matrix representing rotation about an 
%   axis K by an angle THETA
%
%Eric Westervelt
%10/26/2004

R=[k(1)^2*(1-cos(theta))+cos(theta), ...
   k(1)*k(2)*(1-cos(theta))-k(3)*sin(theta), ...
   k(1)*k(3)*(1-cos(theta))+k(2)*sin(theta); 
   k(1)*k(2)*(1-cos(theta))+k(3)*sin(theta), ...
   k(2)^2*(1-cos(theta))+cos(theta), ...
   k(2)*k(3)*(1-cos(theta))-k(1)*sin(theta);
   k(1)*k(3)*(1-cos(theta))-k(2)*sin(theta), ...
   k(2)*k(3)*(1-cos(theta))+k(1)*sin(theta), ...
   k(3)^2*(1-cos(theta))+cos(theta)];
